Martí

In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import xlrd

In [31]:
df = pd.read_excel('ActOp.xlsx')
# df.set_index('Data inicial', inplace=True)
df

,Data inicial,Hora inicial,Data final,Hora final,Total hores,Espai,Estudi,Activitat,Alumnes matriculats,Modalitat docencia,Observacions
0,01/02/2023,08:00,01/02/2023,17:00,9,QC/0011,NaN,600-12 instal·lació videowall,0,,
1,01/02/2023,09:00,01/02/2023,12:00,3,Q3/1007,NaN,958-03 102773 Fonaments de la tecnologia de la...,0,,
2,01/02/2023,09:00,01/02/2023,12:00,3,Q3/1003,NaN,958-03 102773 Fonaments de tecnologia de la in...,0,,
3,01/02/2023,09:00,01/02/2023,15:00,6,Q4/0011,NaN,951-03 102401 Ampliació d'operacions de separació,0,,
4,01/02/2023,10:30,01/02/2023,13:00,2.5,Q4/1005,NaN,1497-20 Revisió d'exàmens,0,,
...,...,...,...,...,...,...,...,...,...,...,...
2976,28/02/2023,18:00,28/02/2023,20:00,2,Q3/0003,10088 Enginyeria Informàtica i Enginyeria de S...,102685 Arquitectura de Computadors i Perifèric...,93,,
2977,,,,,,Q3/0003,10063 Enginyeria Electrònica de Telecomunicació,102685 Arquitectura de Computadors i Perifèric...,93,,
2978,,,,,,Q3/0003,10089 Enginyeria Informàtica i Enginyeria Elec...,102685 Arquitectura de Computadors i Perifèric...,93,,
2979,,,,,,Q3/0003,10100 Enginyeria Electrònica de Telecomunicaci...,102685 Arquitectura de Computadors i Perifèric...,93,,
2980,,,,,,Q3/0003,10064 Enginyeria de Sistemes de Telecomunicació,102685 Arquitectura de Computadors i Perifèric...,93,,

In [32]:
# Drop unnecessary columns

original_df = df.copy()
del df['Data final'], df['Hora final'], df['Modalitat docencia'], df['Observacions']

In [39]:
# Drop redundant rows

for i, r in df.iterrows():
    if r['Data inicial'] == ' ':
        df.drop(i, inplace=True)

df

,Data inicial,Hora inicial,Total hores,Espai,Estudi,Activitat,Alumnes matriculats
0,01/02/2023,08:00,9,QC/0011,NaN,600-12 instal·lació videowall,0
1,01/02/2023,09:00,3,Q3/1007,NaN,958-03 102773 Fonaments de la tecnologia de la...,0
2,01/02/2023,09:00,3,Q3/1003,NaN,958-03 102773 Fonaments de tecnologia de la in...,0
3,01/02/2023,09:00,6,Q4/0011,NaN,951-03 102401 Ampliació d'operacions de separació,0
4,01/02/2023,10:30,2.5,Q4/1005,NaN,1497-20 Revisió d'exàmens,0
...,...,...,...,...,...,...,...
2968,28/02/2023,18:00,1,Q4/1009,10062 Enginyeria Informàtica,102768 Intel·ligència Artificial - 451,Sense grup de matricula
2971,28/02/2023,18:00,1,Q4/1003,10130 Intel·ligència Artificial / Artificial I...,106573 Xarxes Neuronals i Aprenentatge Profund...,Sense grup de matricula
2972,28/02/2023,18:00,1,Q3/0009,10088 Enginyeria Informàtica i Enginyeria de S...,102769 Informació i Seguretat - 453,Sense grup de matricula
2975,28/02/2023,18:00,2,Q2/1009,10105 Gestió de Ciutats Intel·ligents i Sosten...,104539 Seguretat i Privacitat Dels Sistemes d'...,52
2976,28/02/2023,18:00,2,Q3/0003,10088 Enginyeria Informàtica i Enginyeria de S...,102685 Arquitectura de Computadors i Perifèric...,93

In [41]:
# Check for missing info

print(f"We know occupation of {len(list(df[df['Alumnes matriculats'].apply(lambda x: isinstance(x, int)) & df['Alumnes matriculats'] > 0]['Espai'])) / len(list(df['Espai'])) * 100}% activities.")

We know occupation of 41.96625091709464% activities.

In [50]:
# Create a dictionary of studies and their activities

assignatures = {}

for i, r in df.iterrows():
    e = r['Estudi']
    if not pd.isna(e):
        if e not in assignatures.keys():
            assignatures[e] = []
            if (not pd.isna(r['Activitat'])) and (r['Activitat'] not in assignatures[e]):
                assignatures[e].append(r['Activitat'])

print(assignatures) # It's too incomplete

{'6084 Enginyeria de Telecomunicació / Telecommunication Engineering': ['102689 Components i Circuits Electrònics - 311'], '10109 Enginyeria de Dades': ['104361 Aprenentatge Computacional - 811'], '10089 Enginyeria Informàtica i Enginyeria Electrònica de Telecomunicació': ['102747 Sistemes Operatius - 431'], '10065 Enginyeria Química': ['106050 Bases de l\x92Enginyeria Química - 212'], '10062 Enginyeria Informàtica': ["103804 Ètica per a l'Enginyeria - 410"], '10100 Enginyeria Electrònica de Telecomunicació + Enginyeria de Sistemes de Telecomunicació': ['103795 Àlgebra - 33'], '10105 Gestió de Ciutats Intel·ligents i Sostenibles': ['104526 Demografia, Societat i Economia Urbana - 61'], '10088 Enginyeria Informàtica i Enginyeria de Sistemes de Telecomunicació': ['102690 Fonaments de Senyals i Sistemes - 31'], '10064 Enginyeria de Sistemes de Telecomunicació': ['102707 Física Bàsica - 33'], '10063 Enginyeria Electrònica de Telecomunicació': ['102690 Fonaments de Senyals i Sistemes - 311'], '10130 Intel·ligència Artificial / Artificial Intelligence': ['106564 Representació del Coneixement - 71'], '6120 Enginyeria Biològica i Ambiental': ['102444 Simulació de Processos Químics - 21']}

In [64]:
ocus = []

for element in df['Alumnes matriculats']:
    if isinstance(element, int):
        ocus.append(element)

print(len(ocus), len(df['Alumnes matriculats']))

print(max(ocus), min(ocus), np.mean(ocus))

818 1363
151 0 40.13080684596577

In [68]:
df['Alumnes matriculats'][59]

0